= KotlinFixture
Appmattus Limited <info@appmattus.com>
:toc: preamble
:toc-title: Contents
:homepage: https://github.com/appmattus/kotlinfixture
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

https://bintray.com/appmattus/maven/fixture/_latestVersion[image:https://api.bintray.com/packages/appmattus/maven/fixture/images/download.svg[Download]]
https://github.com/appmattus/kotlinfixture/actions[image:https://github.com/appmattus/kotlinfixture/workflows/CI/badge.svg[CI status]]
https://codecov.io/gh/appmattus/kotlinfixture[image:https://codecov.io/gh/appmattus/kotlinfixture/branch/master/graph/badge.svg[Coverage status]]
link:LICENSE.md[image:https://img.shields.io/badge/License-Apache%202.0-blue.svg[License]]


.some description
[%collapsible]
====
[source,kotlin]
._build.gradle.kts_
----
testImplementation("com.appmattus.fixture:fixture:<latest-version>")
----
====


== Getting started

Include the following dependency in your `build.gradle.kts` file:

[source,kotlin]
._build.gradle.kts_
----
testImplementation("com.appmattus.fixture:fixture:<latest-version>")
----

Simply create a fixture and invoke it with the type to be generated:

[source,kotlin]
----
val fixture = kotlinFixture()

// Generate a list of strings
val aListOfStrings = fixture<List<String>>()

// Nulls are supported
val sometimesNull = fixture<Int?>()

// Create instances of classes
// Optional parameters will be randomly used or overridden
data class ADataClass(val value: String = "default")
val aClass = fixture<ADataClass>()

// Abstract classes will pick a sub-class at random
// This could be a Byte, Double, Long, Float, Int or Short
val anyNumber = fixture<Number>()

// Pick randomly from a list
val randomStringFromTheList = fixture(listOf("Cat", "Dog", "Horse"))
val anotherRandomIntFromAList = fixture(1..5)
----

You can also generate an infinite sequence of a type, which you can then
filter:

[source,kotlin]
----
val fixture = kotlinFixture()

val intSequence = fixture.asSequence<Int>()

// Standard Kotlin sequence functions can then be applied before using
// the sequence through an iterator for access to the next() function.

// For example, you can filter values
val oddIterator = intSequence.filter { it.absoluteValue.rem(2) == 1 }.iterator()
val oddNumber = oddIterator.next()
val anotherOddNumber = oddIterator.next()

// Or, ensure it returns only distinct values
enum class XYZ { X, Y, Z }
val enumIterator = fixture.asSequence<XYZ>().distinct().iterator()
val aDistinctValue = enumIterator.next()
val anotherDistinctValue = enumIterator.next()
----

WARNING: As the sequence is infinite, distinct will hang if no more distinct values can be generated.

Everything can be customised, see link:fixture/configuration-options.adoc[configuration options] for more details.

== Kotest integration

https://github.com/kotest/kotest/[Kotest] supports
https://github.com/kotest/kotest/blob/master/doc/reference.md#property-based-testing-[property testing],
but to use it with more than just the few basic types built
into the library requires you to create your own custom generators which
you then provide.

[source,kotlin]
._build.gradle.kts_
----
// Add for Kotest integration
testImplementation("com.appmattus.fixture:fixture-kotest:<latest-version>")
----

Including the `fixture-kotest` dependency in your project adds extension
functions `checkAll` and `forAll` to the fixture. These
functions wrap the equivalent functions from Kotest while providing
generation of all the classes
https://github.com/appmattus/kotlinfixture[KotlinFixture] supports.
For example:

[source,kotlin]
----
data class Person(name: String, age: Int)

fixture.checkAll { person1: Person, person2: Person ->
   person1 shouldNotBeSameInstanceAs person2
}
----

== Java Faker integration

The http://dius.github.io/java-faker/[Java Faker] library generates
fake data, useful if you need to generate objects with pretty data.

[source,kotlin]
._build.gradle.kts_
----
// Add for Java Faker integration
testImplementation("com.appmattus.fixture:fixture-javafaker:<latest-version>")
----

Including the `fixture-javafaker` dependency in your project adds a
`javaFakerStrategy` which uses
http://dius.github.io/java-faker/[Java Faker] to populate named
properties such as `name`, `city` and `phoneNumber`. A full list of
supported properties and how they map to
http://dius.github.io/java-faker/[Java Faker] can be found in
`link:fixture-javafaker/src/main/kotlin/com/appmattus/kotlinfixture/decorator/fake/javafaker/JavaFakerConfiguration.kt[JavaFakerConfiguration]`.

[source,kotlin]
----

val fixture = kotlinFixture {
    javaFakerStrategy()
}

data class Person(val name: String, val age: Long)

println(fixture<Person>()) // Person(name=Keneth Bartoletti, age=54)
----

Additionally, the `javaFakerStrategy` function allows you to override
faker settings such as `locale`. The available options can be found in
`link:fixture-javafaker/src/main/kotlin/com/appmattus/kotlinfixture/decorator/fake/javafaker/JavaFakerConfigurationBuilder.kt[JavaFakerConfigurationBuilder]`.

=== Generate strings based on a regex

The module also introduces the ability to generate a random string from
a Regex, with no need to enable the faker functionality:

[source,kotlin]
----
data class DataClass(val index: String, val value: String)

val indexRegex = "[a-z][0-9]".toRegex()
val valueRegex = "[A-Z]{3}".toRegex()

val fixture = kotlinFixture {
    factory<String> { regexify(indexRegex) }

    property(DataClass::value) { regexify(valueRegex) }
}

println(fixture<DataClass>()) // DataClass(index=m3, value=CGJ)
----

IMPORTANT: Be careful with object creation inside the generation function as it
will be called for every instance of the object you create.

== Related projects

* Marcello Galhardo's https://github.com/marcellogalhardo/kotlin-fixture[Kotlin.Fixture].
* FlexTrade's https://github.com/FlexTradeUKLtd/kfixture[KFixture] wrapper for https://github.com/FlexTradeUKLtd/jfixture[JFixture].
* Jeasy's https://github.com/j-easy/easy-random[Easy Random],

Please take a look at the feature link:fixture/comparison.adoc[comparison with related projects].

== Contributing

Please fork this repository and contribute back using
https://github.com/appmattus/kotlinfixture/pulls[pull requests].

All contributions, large or small, major features, bug fixes, additional
language translations, unit/integration tests are welcome.

== License

link:LICENSE.md[image:https://img.shields.io/badge/License-Apache%202.0-blue.svg[License]]

Copyright 2020 Appmattus Limited

Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License. You may obtain
a copy of the License at
https://www.apache.org/licenses/LICENSE-2.0[https://www.apache.org/licenses/LICENSE-2.0].

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
