== Java Faker integration
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

[source,kotlin]
._build.gradle.kts_
----
// Add for Java Faker integration
testImplementation("io.github.detomarco.kotlinfixture:fixture-datafaker:<latest-version>")
----

The http://dius.github.io/java-faker/[Java Faker] library generates
fake data, useful if you need to generate objects with pretty data.

Including the `fixture-datafaker` dependency in your project adds a
`dataFakerStrategy` which uses
http://dius.github.io/java-faker/[Java Faker] to populate named
properties such as `name`, `city` and `phoneNumber`. A full list of
supported properties and how they map to
http://dius.github.io/java-faker/[Java Faker] can be found in
`link:src/main/kotlin/io/github/detomarco/kotlinfixture/datafaker/DataFakerConfiguration.kt[DataFakerConfiguration]`.

[source,kotlin]
----

val fixture = kotlinFixture {
    dataFakerStrategy()
}

data class Person(val name: String, val age: Long)

println(fixture<Person>()) // Person(name=Keneth Bartoletti, age=54)
----

Additionally, the `dataFakerStrategy` function allows you to override
faker settings such as `locale`. The available options can be found in
`link:src/main/kotlin/io/github/detomarco/kotlinfixture/datafaker/DataFakerConfigurationBuilder.kt[DataFakerConfigurationBuilder]`.
