== Java Faker support

[source,kotlin]
----
// Add for Java Faker integration
testImplementation("com.appmattus.fixture:fixture-javafaker:<latest-version>")
----

The http://dius.github.io/java-faker/[Java Faker] library generates
fake data, useful if you need to generate objects with pretty data.

Including the `fixture-javafaker` dependency in your project adds a
`javaFakerStrategy` which will use
http://dius.github.io/java-faker/[Java Faker] to populate named
properties such as `name`, `city` and `phoneNumber`. A full list of
supported properties and how they map to
http://dius.github.io/java-faker/[Java Faker] can be found in
link:src/main/kotlin/com/appmattus/kotlinfixture/decorator/fake/javafaker/JavaFakerConfiguration.kt[JavaFakerConfiguration].

Additionally, the `javaFakerStrategy` function allows you to override
faker settings such as `locale`.

[source,kotlin]
----

val fixture = kotlinFixture {
    javaFakerStrategy()
}

data class Person(val name: String, val age: Long)

println(fixture<Person>()) // Person(name=Keneth Bartoletti, age=54)
----

=== Regex to String generation

The module also introduces the ability to generate a random string from
a Regex, with no need to enable the faker functionality:

[source,kotlin]
----
data class DataClass(val index: String, val value: String)

val indexRegex = "[a-z][0-9]".toRegex()
val valueRegex = "[A-Z]{3}".toRegex()

val fixture = kotlinFixture {
    factory<String> { regexify(indexRegex) }

    property(DataClass::value) { regexify(valueRegex) }
}

println(fixture<DataClass>()) // DataClass(index=m3, value=CGJ)
----
