== Java Faker integration
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

[source,kotlin]
._build.gradle.kts_
----
// Add for Java Faker integration
testImplementation("com.appmattus.fixture:fixture-javafaker:<latest-version>")
----

The http://dius.github.io/java-faker/[Java Faker] library generates
fake data, useful if you need to generate objects with pretty data.

Including the `fixture-javafaker` dependency in your project adds a
`javaFakerStrategy` which uses
http://dius.github.io/java-faker/[Java Faker] to populate named
properties such as `name`, `city` and `phoneNumber`. A full list of
supported properties and how they map to
http://dius.github.io/java-faker/[Java Faker] can be found in
`link:src/main/kotlin/com/appmattus/kotlinfixture/decorator/fake/javafaker/JavaFakerConfiguration.kt[JavaFakerConfiguration]`.

[source,kotlin]
----

val fixture = kotlinFixture {
    javaFakerStrategy()
}

data class Person(val name: String, val age: Long)

println(fixture<Person>()) // Person(name=Keneth Bartoletti, age=54)
----

Additionally, the `javaFakerStrategy` function allows you to override
faker settings such as `locale`. The available options can be found in
`link:src/main/kotlin/com/appmattus/kotlinfixture/decorator/fake/javafaker/JavaFakerConfigurationBuilder.kt[JavaFakerConfigurationBuilder]`.

=== Generate strings based on a regex

The module also introduces the ability to generate a random string from
a Regex, with no need to enable the faker functionality:

[source,kotlin]
----
data class DataClass(val index: String, val value: String)

val indexRegex = "[a-z][0-9]".toRegex()
val valueRegex = "[A-Z]{3}".toRegex()

val fixture = kotlinFixture {
    factory<String> { regexify(indexRegex) }

    property(DataClass::value) { regexify(valueRegex) }
}

println(fixture<DataClass>()) // DataClass(index=m3, value=CGJ)
----

IMPORTANT: Be careful with object creation inside the generation function as it
will be called for every instance of the object you create.
